project:
  type: book
  title: "load"
  
book:
  title: "Forflyttning med oppakning"
  author: "Sjur Fortun Ã˜fsteng"
  date: "2026-01-01"
  search: true
  repo-url: https://github.com/sjurjo/mit-load
  repo-branch: master
  repo-actions: [edit, issue, source]
  downloads: [epub]
  chapters:
  - index.qmd
  - 01-intro.qmd
  - part: "Data visulisering"
    chapters: 
    - 02-data.qmd
  - 99-refs.qmd
   

brand: _brand.yml
bibliography: resources/bib.bib
format:
  html:
    reference-location: margin
    citation-location: margin
    footnotes-hover: false
    theme:
      light: flatly
      dark: darkly
  #epub:
   # cover-image: resources/cover.png