project:
  type: book
  title: "load"
  
book:
  title: "Forflytning med oppakning"
  author: "Sjur Fortun Ã˜fsteng"
  date: "last-modified"
  search: true
  repo-url: https://github.com/sjurjo/mit-load
  repo-branch: master
  #repo-actions: [edit, issue, source]
  downloads: [epub]
  chapters:
  - index.qmd
  - part: "Forflytning"
    chapters:
    - 01-intro.qmd
  - part: "Data Visulisering"
    chapters: 
    - 02-data.qmd
  - 99-refs.qmd
   

brand: _brand.yml
bibliography: resources/bib.bib
format:
  html:
    reference-location: margin
    citation-location: margin
    footnotes-hover: false
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right
    code-tools:
      source: true
      toggle: false
      caption: none
code-block-bg: true
code-block-border-left: "#31BAE9"
highlight-style: atom-one
   
  #epub:
   # cover-image: resources/cover.png
   
   
   